In [13]:
import torch
data = torch.tensor([[2,3,224,224],[2, 4, 5, 8]])
data

tensor([[  2,   3, 224, 224],
        [  2,   4,   5,   8]])

In [2]:
data2 = torch.ones_like(data, dtype=torch.float)
data2
print(data2)
data3 = torch.zeros_like(data, dtype=torch.float64)
print(data3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [3]:
data3.dtype

torch.float64

In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape, dtype=torch.float64)
print(rand_tensor)
rand_tensor1 = torch.randn(shape, dtype=torch.float64)
print(rand_tensor1)
print(rand_tensor.size())

tensor([[0.6654, 0.0060, 0.4682],
        [0.7218, 0.7890, 0.4860]], dtype=torch.float64)
tensor([[ 0.2291, -0.2962,  1.0932],
        [-0.5130,  0.1062, -1.4959]], dtype=torch.float64)
torch.Size([2, 3])


In [5]:
data4 = torch.rand(3,4, device=torch.device('cpu'))
print(data4.shape)
print(data4.dtype)
print(data4.device)

torch.Size([3, 4])
torch.float32
cpu


In [6]:
print(torch.cuda.is_available())

False


In [7]:
if torch.cuda.is_available():
    device = torch.device('cuda:0')
    data4.to(device)
print(data4)
print(data4.device)

tensor([[0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763]])
cpu


In [8]:
data4 = torch.cat([data4, data4, data4])
print(data4)

tensor([[0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763],
        [0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763],
        [0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763]])


In [9]:
rand_tensor

tensor([[0.6654, 0.0060, 0.4682],
        [0.7218, 0.7890, 0.4860]], dtype=torch.float64)

In [10]:
tenser = torch.tensor([[1,2,3,4,5],[3,4,5,6,7]], dtype=torch.int)
tenser.add_(5)
print(tenser)

tensor([[ 6,  7,  8,  9, 10],
        [ 8,  9, 10, 11, 12]], dtype=torch.int32)


In [14]:
import torch
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=True)

'expression.png'